"""empty message

Revision ID: 7e2c84df8d94
Revises: 
Create Date: 2023-03-17 09:27:08.580038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2c84df8d94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alumnos',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('alumno_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('username')
    )
    op.create_table('empresas',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('empresa_nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Integer(), nullable=True),
    sa.Column('ingles', sa.Integer(), nullable=True),
    sa.Column('aleman', sa.Integer(), nullable=True),
    sa.Column('frances', sa.Integer(), nullable=True),
    sa.Column('capacidad_analitica', sa.Integer(), nullable=True),
    sa.Column('trabajo_equipo', sa.Integer(), nullable=True),
    sa.Column('comunicacion', sa.Integer(), nullable=True),
    sa.Column('pensamiento_critico', sa.Integer(), nullable=True),
    sa.Column('inovacion', sa.Integer(), nullable=True),
    sa.Column('liderazgo', sa.Integer(), nullable=True),
    sa.Column('decision_making', sa.Integer(), nullable=True),
    sa.Column('problem_solving', sa.Integer(), nullable=True),
    sa.Column('marketing', sa.Integer(), nullable=True),
    sa.Column('e_commerce', sa.Integer(), nullable=True),
    sa.Column('diseno_grafico', sa.Integer(), nullable=True),
    sa.Column('matematicas', sa.Integer(), nullable=True),
    sa.Column('estadistica', sa.Integer(), nullable=True),
    sa.Column('gestion_proyectos', sa.Integer(), nullable=True),
    sa.Column('redes_sociales', sa.Integer(), nullable=True),
    sa.Column('sostenibilidad', sa.Integer(), nullable=True),
    sa.Column('inteligencia_artificial', sa.Integer(), nullable=True),
    sa.Column('big_data', sa.Integer(), nullable=True),
    sa.Column('machine_learning', sa.Integer(), nullable=True),
    sa.Column('analisis_datos', sa.Integer(), nullable=True),
    sa.Column('bases_datos', sa.Integer(), nullable=True),
    sa.Column('cloud', sa.Integer(), nullable=True),
    sa.Column('intenet_of_things', sa.Integer(), nullable=True),
    sa.Column('networks', sa.Integer(), nullable=True),
    sa.Column('sistemas_operativos', sa.Integer(), nullable=True),
    sa.Column('web_desarrollo', sa.Integer(), nullable=True),
    sa.Column('web_diseno', sa.Integer(), nullable=True),
    sa.Column('r', sa.Integer(), nullable=True),
    sa.Column('java', sa.Integer(), nullable=True),
    sa.Column('pascal', sa.Integer(), nullable=True),
    sa.Column('python', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.alumno_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id')
    )
    op.create_table('ofertas',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empresa_nombre', sa.String(), nullable=True),
    sa.Column('job_tittle', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Integer(), nullable=True),
    sa.Column('ingles', sa.Integer(), nullable=True),
    sa.Column('aleman', sa.Integer(), nullable=True),
    sa.Column('frances', sa.Integer(), nullable=True),
    sa.Column('trabajo_equipo', sa.Integer(), nullable=True),
    sa.Column('comunicacion', sa.Integer(), nullable=True),
    sa.Column('matematicas', sa.Integer(), nullable=True),
    sa.Column('estadistica', sa.Integer(), nullable=True),
    sa.Column('gestion_proyectos', sa.Integer(), nullable=True),
    sa.Column('sostenibilidad', sa.Integer(), nullable=True),
    sa.Column('big_data', sa.Integer(), nullable=True),
    sa.Column('programacion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('nombre_contacto', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.alumno_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('alumno_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas')
    op.drop_table('cv')
    op.drop_table('empresas')
    op.drop_table('alumnos')
    op.drop_table('admin')
    # ### end Alembic commands ###
