"""empty message

Revision ID: 909bab154ad4
Revises: 
Create Date: 2022-06-09 16:43:01.260465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909bab154ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas_nuevas',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empresa_nombre', sa.String(), nullable=True),
    sa.Column('job_tittle', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Integer(), nullable=True),
    sa.Column('ingles', sa.Integer(), nullable=True),
    sa.Column('aleman', sa.Integer(), nullable=True),
    sa.Column('frances', sa.Integer(), nullable=True),
    sa.Column('trabajo_equipo', sa.Integer(), nullable=True),
    sa.Column('comunicacion', sa.Integer(), nullable=True),
    sa.Column('matematicas', sa.Integer(), nullable=True),
    sa.Column('estadistica', sa.Integer(), nullable=True),
    sa.Column('gestion_proyectos', sa.Integer(), nullable=True),
    sa.Column('sostenibilidad', sa.Integer(), nullable=True),
    sa.Column('big_data', sa.Integer(), nullable=True),
    sa.Column('programacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas_nuevas')
    # ### end Alembic commands ###
