"""empty message

Revision ID: b085697a46cc
Revises: 
Create Date: 2022-03-25 17:16:31.813171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b085697a46cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alumnos', ['email'])
    op.create_unique_constraint(None, 'alumnos', ['username'])
    op.create_unique_constraint(None, 'alumnos', ['telefono'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alumnos', type_='unique')
    op.drop_constraint(None, 'alumnos', type_='unique')
    op.drop_constraint(None, 'alumnos', type_='unique')
    # ### end Alembic commands ###
