"""empty message

Revision ID: e7bc6c45083b
Revises: 
Create Date: 2022-06-28 19:37:09.078197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bc6c45083b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empresa_nombre', sa.String(), nullable=True),
    sa.Column('job_tittle', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('grado', sa.Integer(), nullable=True),
    sa.Column('nota_media', sa.Integer(), nullable=True),
    sa.Column('ingles', sa.Integer(), nullable=True),
    sa.Column('aleman', sa.Integer(), nullable=True),
    sa.Column('frances', sa.Integer(), nullable=True),
    sa.Column('trabajo_equipo', sa.Integer(), nullable=True),
    sa.Column('comunicacion', sa.Integer(), nullable=True),
    sa.Column('matematicas', sa.Integer(), nullable=True),
    sa.Column('estadistica', sa.Integer(), nullable=True),
    sa.Column('gestion_proyectos', sa.Integer(), nullable=True),
    sa.Column('sostenibilidad', sa.Integer(), nullable=True),
    sa.Column('big_data', sa.Integer(), nullable=True),
    sa.Column('programacion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.alumno_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('alumno_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas')
    # ### end Alembic commands ###
